name: C/C++ CI (Windows x64)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}  # Use MSYS2 environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2 (MinGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-glfw
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-toolchain

      - name: Build
        run: mingw32-make

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: Corsprite-launcher-x64
          path: Corsprite_launcher.exe

      - name: Clean
        run: |
          rm -f Corsprite_launcher.exe
